name: PlatformIO CI Linting

on:

   push:
    branches:
        - main 
    paths:
        - "./src"
        - "./test"
        - "./include"
        - "./lib"
   pull_request:
    branches:
        - main
    paths:
        - "./src"
        - "./test"
        - "./include"
        - "./lib"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install CppLint
        run : |
            python -m pip install --upgrade pip
            pip install cpplint
      - name: Lint code
        run: cpplint --repository=. --recursive --filter=+build/c++11,+readability/braces,-legal,-build/include./include ./lib ./src ./test
